name = "webAsteroids"
default_targets = ["win64", "lovejs", "macos"]
build_directory = "build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-screenshots/**",     
    "-README.md",          
    "-assets/asefiles/**",
    "-.gitignore",
    "-push.sh",
]

love_version = "11.5"
icon_file = "assets/icon.png"